### ISSUE TITLE
Abstract protocol prevents conforming in swift 1.2

### ISSUE THREAD

**Issue by haswalt** [abury/ABPadLockScreen#45]
Because of the abstract decleration of the protocol it's impossible to confirm to the ABPadLockScreenViewControllerProtocol because:

1) Only declaring 1 method fails. The abstract method is also required to conform.
2) Declaring both methods causes build errors due to duplicate method declerations.

We removed the abstract protocol from our fork to make it work in swift but that's not ideal. Secondly I'd like to know more why there is the abstract? It doesn't seem to provide a great deal other than confusion and 2 places for the code to reside.

**Comment by abury** [comment]
Hey @haswalt 
Thanks for letting me know these issues. I haven't had a chance to make it play nice with swift yet, but I got a PR the same day you wrote this that apparently fixes up the issues so I'll probably use that.
Regarding the protocol abstraction, there were two logical protocols for the setup and implementation delegates that had separate methods, but both shared the need for a  'unlockWasCancelled'. In an effort to keep it DRY I decided to create an abstract protocol. Whilst this technically solved that issue, it has probably caused more issues than it has resolved, but that's the beauty of hindsight ;)

I'll check out your PR over the next few days. Is there a time frame you'd prefer this to be done by?

**Comment by haswalt** [comment]
Thanks @abury yeah my colleague submitted my changes as  PR right after I posted this bug.

**Comment by abury** [comment]
This has been resolved in PR #48

**Comment by ryanmeisters** [comment]
I seem to be having this issue still with version 3.3.0 with Swift 1.2.. @haswalt @abury any pointers?

I have a view controller that conforms to `ABPadLockScreenViewControllerDelegate` by implementing 

```swift
func padLockScreenViewController(padLockScreenViewController: ABPadLockScreenViewController!, validatePin pin: String!) -> Bool
func unlockWasSuccessfulForPadLockScreenViewController(padLockScreenViewController: ABPadLockScreenViewController!)
func unlockWasUnsuccessful(falsePin: String!, afterAttemptNumber attemptNumber: Int, padLockScreenViewController: ABPadLockScreenViewController!)
func unlockWasCancelledForPadLockScreenViewController(padLockScreenViewController: ABPadLockScreenViewController!) 
func attemptsExpiredForPadLockScreenViewController(padLockScreenViewController: ABPadLockScreenViewController!)
```

But I still get a compiler error saying 

> Type 'MainViewController' does not conform to protocol ABPadLockScreenDelegate

Of course, if I try to conform to `ABPadLockScreenDelegate` by implementing 

```swift
func unlockWasCancelledForPadLockScreenViewController(padLockScreenViewController: ABPadLockScreenAbstractViewController!)
``` 
the compiler complains about the conflicting `unlockWasCancelledForPadLockScreenViewController:` methods.

**Comment by abury** [comment]
Hey @ryanmeisters 

I havne't had much of a chance to test this on any swift codebase yet. I've been changing jobs, moving countries and having issues with my GCC thats stopping me from compiling in the command line (which means I can't push new versions of this to cocoa pods) and the only way to resolve this is to do a complete reinstall.

It should start to slow down in the next week and i'm hoping to have a look at this in Swift and push a version thats more compatible. (Will probably update the example to use Swift as well)

In the mean time @haswalt will hopefully be able to guide us in the right direction.

**Comment by Jayvd** [comment]
Yeah, I have this problem too. Please help us. @haswalt @abury @ryanmeisters 

Thanks for providing this beautiful control in the first place!

**Comment by Jayvd** [comment]
hi @ryanmeisters , did you manage to solve the problem?

**Comment by Jayvd** [comment]
Any updates @haswalt @abury @ryanmeisters ? I couldn't seem to find a replacement library that offer functionality as good as this one.

**Comment by abury** [comment]
@Jayvd well as happy as I am that this seems to be the best library, i'm sorry that I haven't managed to keep it up to date enough for you :disappointed: Life has been a bit crazy in the last few months after changing jobs and moving overseas and I haven't had the time to do it that i'd like.
I have my first weekend free in a long time this weekend, and a computer that properly runs GCC. I will do my very best to get it updated this weekend for you, with a swift example project.

I'm sorry again for taking so long and thanks so much for your patience :smile:

**Comment by abury** [comment]
This will be resolved in 3.4.0, to be released very soon.

**Comment by Jayvd** [comment]
Cool, thanks! @abury
